VAGRANTFILE_API_VERSION = "2"
disk = '/tmp/disk.vdi'
# https://atlas.hashicorp.com/puppetlabs

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-16.04-64-nocm"
  config.vm.network :private_network, ip: "192.168.100.87"
  config.vm.hostname = "ftp"

  config.vm.provider :virtualbox do |v|
    v.name = "ip87_ftp"
    v.memory = 512
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    # Create a new disk
    unless File.exist?(disk)
    v.customize ['createhd', '--filename', disk, '--size', 100 * 1024]
    end
    v.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
  end
end
